<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>
</div>

<?php/* $cats =  $this->helper('Excellence\Hello\Helper\Newdata')->getCurrentProduct(); 
echo $cats;
	if($cats == 'Bags')
	{
        $imgurl = $this->getUrl('media/pdp-catalog-pdf') . "timberVault-mirror-installation-instructions.pdf";
        echo "<i class='fa fa-file-pdf-o' aria-hidden='true'></i><a href='".$imgurl ,array('_secure'=>true)."' class='instrucPDF'>TimberVault Mirror Installation Instructions</a>";

	}
	elseif ($cats == 'Fitness Equipment') {
	    $imgurl = $this->getUrl('media/pdp-catalog-pdf') . "timberVault-shelf-installation-instructions.pdf";
        echo "<i class='fa fa-file-pdf-o' aria-hidden='true' style='color: red; font-size: 21px;'></i><a href='".$imgurl."' target='_blank' class='instrucPDF'>TimberVault Shelf Installation Instructions</a>";
	}*/
	

?>

5200164150

