<?php
	$themeHelper = $this->helper('MGS\Social\Helper\Data');
	$user_name = $themeHelper->getUserName(); 
	$client_id = $themeHelper->getClientId(); 
	$number = $themeHelper->getNumber(); 
	$width = $themeHelper->getWidth();
	$height = $themeHelper->getHeight();
?>
<?php if($themeHelper->getEnable() && $user_name && $client_id && $number): ?>
<div class="instagram">
	<div class="block-title">
		<p><?php echo $this->getTitle(); ?></p>
	</div>
	<div class="note-text">
		<span><?php echo $this->getNoteText(); ?></span>
	</div>
	<div class="instagram-carousel">
		<?php $block->getInstagramData($user_name, $client_id, $number, $width, $height); ?>
	</div>
</div>
<?php else: ?>
	<p><?php echo __('The instagram extension had disabled or no "User Name" or no "Client ID" or no "Number of Images want to show" ') ?></p>
<?php endif; ?>
